"""add_indexes

Revision ID: bb33807fdccb
Revises: 2a0aeee3ba0e
Create Date: 2026-05-15 15:43:11.431211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb33807fdccb'
down_revision: Union[str, Sequence[str], None] = '2a0aeee3ba0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_index(op.f('ix_stats_created_at'), 'stats', ['created_at'], unique=False)
    op.create_index(op.f('ix_stats_device_id'), 'stats', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stats_device_id'), table_name='stats')
    op.drop_index(op.f('ix_stats_created_at'), table_name='stats')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    # ### end Alembic commands ###
